#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BackupKodiSettings.Resource", IsApplication=true)]

namespace BackupKodiSettings
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int kodi = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sdicon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int SportsDonkey = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SportsDonkey1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int SportsDonkey2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ssd2 = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int btnBackup = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int btnBackupSD = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int btnCheckBackupDir = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int btnCheckFavourites = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int btnCheckXonfluence = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int btnCreateBackupDir = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int btnDeleteBackupDir = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int btnGetPulsePin = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int btnLaunchKodi = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int btnRestore = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int btnRestoreSD = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int btnSDPaths = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int btnViewFavourites = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int btnViewXonfSettings = 2131165204;
			
			// aapt resource value: 0x7f070019
			public const int get_pulse_pin = 2131165209;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout1 = 2131165188;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout2 = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int pbarPulsePin = 2131165191;
			
			// aapt resource value: 0x7f070011
			public const int progressBar1 = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int scrollView1 = 2131165205;
			
			// aapt resource value: 0x7f070009
			public const int swiShowTestButtons = 2131165193;
			
			// aapt resource value: 0x7f070017
			public const int test_buttons = 2131165207;
			
			// aapt resource value: 0x7f070012
			public const int toolbar = 2131165202;
			
			// aapt resource value: 0x7f070006
			public const int txtPulsePin = 2131165190;
			
			// aapt resource value: 0x7f070016
			public const int txtSettingsView = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int view_settings_files = 2131165208;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TestButtons = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int toolbar = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ViewSettings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int DebugMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int GetPulsePin = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int Help = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int TestButtons = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ViewSettingsFiles = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
